name: add-some-function
description: teste um plugin
display-name: add-some-function
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
# inputs:
#   - label: Input Example
#     type: text
#     name: example
#     default: any text
hooks:
  - type: edit
    path: "{{project_name}}.txt"
    trigger: after-render
    changes:
      - insert: 
          line: -1
          snippet: snippets/example.txt